export const array = [
  {
    title: "Departamento 1 Ambiente - Barrio Norte, Capital Federal",
    adress: " Azucena Villaflor 500",
    city: " Buenos Aires",
    country: " Argentina",
    locate: "Av.Las Heras",
    description:
      "Derpartamento ubicado en RECOLETA. Próximo a las Avenidas Coronel Diaz , Avda las Heras. Cerca de todos los medios de transporte. Zona residencial y comercial. Cercano a los Hospitales Rivadavia y Aleman La unidad es un MONOAMBIENTE con espacio guardado., Cocina y baño completo.Calefon individual.",
    available: true,
    meters: " 35m²",
    rooms: " 2 Habitaciones",
    bathrooms: " 2 Baños",
    enviroments: " 3 Ambientes ",
    category: " Departamento",
    operation: "Alquiler",
    price: " 45.509 ARGS",
    image:
      "https://imgar.zonapropcdn.com/avisos/1/00/49/30/94/03/360x266/1799091787.jpg",
  },
  {
    title: "Venta. 4 Ambientes. Cochera. French y Anchorena.",
    adress: "French 2600",
    city: " Buenos Aires",
    country: "Argentina",
    locate: " Av.Las Heras",
    description:
      "Dormitorio 1: 2,80 x 3,80 m. Dormitorio 2: 3,32 x 2,40 m. Dormitorio 3: 2,05 x 4,15 m. Living: 2,92 x 7,66 m. Balcón corrido: 1,20 x 8 m. Hall comunicador: 1,83 de 2,95 m. Baño Principal: 1,87 x 2,30 m. Baño: 0,95 x 1,50 m. Cocina: 2,05 x 4,15 m.",
    available: true,
    rooms: " 3 Habitaciones",
    bathrooms: " 1 Baño",
    enviroments: " 3 Ambientes",
    category: " Departamento",
    operation: " Venta",
    price: " 200.000 USD",
    image:
      "https://imgar.zonapropcdn.com/avisos/1/00/50/57/88/67/360x266/1838666215.jpg",
  },
  {
    title: "French 2600 y Anchorena: Lindisimo con Balcon",
    adress: "French al 2600",
    city: "Buenos Aires",
    country: "Argentina",
    locate: "French",
    description:
      "semipiso palier individual luminoso buen estado  general, 2 dormitorios  con 2 baños, uno en suite.  Luz y Sol, muy buen pulmón. ",
    available: true,
    meters: "70m²",
    rooms: " 2 Ambientes",
    bathrooms: " 2 Baños",
    enviroments: " 3 Habitaciones",
    category: "Departamento",
    operation: "Alquiler",
    price: "60.700 ARGS",
    image:
      "https://imgar.zonapropcdn.com/avisos/1/00/50/70/63/46/360x266/1841585167.jpg",
  },
  {
    title: "Departamento · 51m² · 2 Ambientes ",
    adress: "Carranza al 1300",
    city: "Buenos Aires",
    country: "Argentina",
    locate: "Palermo",
    description:
      "Espectacular 2 ambientes TOTALMENTE AMOBLADO, a estrenar en el Complejo Vitta Carranza en PalermoEdificio de 9 pisos, departamento con cochera y baulera.Dormitorio en suite - VestidorToilette de recepciónGRAN BALCON CON JARDIN!!!Seguridad presencial las 24 hsCalefacción individual por losa radianteNo apto mascotasAmenities AAA: Piscina externa - SUM - Gimnasio - Business Center - Jardín - Acceso a cocheras por rampa - LoundryPara los casos de alquiler de vivienda, el monto máximo de comisión que se le puede requerir a los propietarios será el equivalente al cuatro con quince centésimos por ciento (4,15%) del valor total del respectivo contrato. Se encuentra prohibido cobrar a los inquilinos que sean personas físicas comisiones inmobiliarias y gastos de gestoría de informes (incorporado como inciso 8 del artículo 10 de la Ley 2340).Tenga en cuenta que la nueva ley de alquileres N° 27.551 no deroga las leyes de cada jurisdicción respecto de los honorarios que pueden percibirse. Además le hacemos saber que el IVC, está monitoreando todas las publicaciones y está realizando denuncias en nuestra Institución, que son pasibles de sanción.Las descripciones, medidas, superficies y proporciones consignadas en esta ficha son aproximadas, sólo se muestran a modo orientativo.Matriculado CUCICBA N°923",
    available: false,
    meters: "63m²",
    rooms: " 2 Ambientes",
    bathrooms: " 1 Baño",
    enviroments: " 1 Habitacion",
    category: "Departamento",
    operation: "Alquiler",
    price: "4550 USD",
    image:
      "https://imgar.zonapropcdn.com/avisos/1/00/51/17/32/37/360x266/1855648097.jpg",
  },
  {
    title:
      "Alquiler Departamento 2 Amb C/cochera en Torre de Categoria C/amenities - Palermo",
    adress: "Thames al 2300",
    city: "Buenos Aires",
    country: "Argentina",
    locate: "Palermo",
    description:
      "Inmejorable departamento 2 ambientes con cochera. Piso alto con vista abierta a toda la ciudad, super luminoso con amplio balcon y ventanales.Ubicado en el corazon de Palermo Soho.Hall de recepcion, amplio living con cocina integrada y salida al balcon, baño completo, comodo dormitorio con placar completo y gran ventanal.La unidad posee A/A frío calor en living y dormitorio.Cochera descubierta en PB.Excelente estado y listo para mudarse!",
    available: false,
    meters: "63m²",
    rooms: " 2 Ambientes",
    bathrooms: " 1 Baño",
    enviroments: " 1 Habitacion",
    category: "Departamento",
    operation: "Alquiler",
    price: "750 USD",
    image:
      "https://imgar.zonapropcdn.com/avisos/1/00/51/20/17/88/360x266/1856206421.jpg",
  },

  {
    title: "Caba Recoleta Alquiler Departamento Ulrich Propiedades",
    adress: "Pacheco de Melo 1967",
    city: "Buenos Aires",
    country: "Argentina",
    locate: "Recoleta",
    description:
      "Lindísimo departamento en pleno recoleta. Cuenta con 3 dormitorios, 3 baños, amplios placards, hall distribuidor, living comedor en L a balcón, gran cocina con espacio para comedor de diario. Pisos de parquet. Doble circulación.Calefacción central, split en living comedor.",
    available: false,
    meters: "115m²",
    rooms: " 4 Ambientes",
    bathrooms: " 3 Baños",
    enviroments: " 3 Habitaciones",
    category: "Departamento",
    operation: "Alquiler",
    price: "950 USD + $ 45.000 Expensas",
    image:
      "https://imgar.zonapropcdn.com/avisos/1/00/50/60/77/27/360x266/1838510919.jpg",
  },
];
